#!/usr/bin/env python

#
# Python script that implements a Git Hook of type Pre Push
# Author: Alexandre Pardo
# Date: 06/26/2019
#

import json, os, re, sys
from subprocess import check_call

print '==================================='
print '  GIT PRE-PUSH HOOK FOR LINT/TEST'
print '==================================='

try:

	package_json_file_name = 'package.json'
	is_npm_project = os.path.isfile(package_json_file_name)

	if not is_npm_project: # Nothing to do
		# Nothing to do
		sys.exit(0)

	package_json_content = open(package_json_file_name).read()
	package_json = json.loads(package_json_content)

	scripts = package_json['scripts']

	has_lint = 'lint' in scripts
	if has_lint:
		check_call('npm run lint', shell=True)

	has_test = 'test' in scripts
	if has_test:
		check_call('npm run test', shell=True)
except Exception as e:
	# Oops, either lint or test failed.
	print 'EXCEPTION THROWN ON PRE-PUSH HOOK', e
	sys.exit(1)
