#!/usr/bin/env python
import sys, re
from subprocess import check_call

print '=========='
print '=GIT HOOK='
print '=========='
print '\nRunning lint and test before pushing the code to remote repository\n\n'

try:
	check_call('npm run lint && npm run test', shell=True)
except:
	sys.exit(1)
